dev:

  cui:
    addresses:
      - 10.1.10.10
      - 10.1.10.11

  adminui:
    addresses:
      - 10.1.10.20
      - 10.1.10.21

  api:
    addresses:
      - 10.2.10.10
      - 10.2.10.11

  db:
    addresses:
      - 10.8.10.10
      - 10.8.10.11
